# Generated by Django 3.1.5 on 2021-02-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HEX', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(choices=[('1', 'Todos los días'), ('15', 'Cada quince días'), ('30', 'Al mes')], default='30', max_length=200)),
                ('tiempo', models.CharField(choices=[('183', 'Medio año'), ('365', 'Un año'), ('730', 'Dos años'), ('1825', 'Cinco años')], default='365', max_length=200)),
                ('meta', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='user/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrePlazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiempo', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(max_length=200)),
                ('meta', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahorro.color')),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('1', 'Todos los días'), ('15', 'Cada quince días'), ('30', 'Al mes')], default='30', max_length=200)),
                ('tiempo', models.CharField(choices=[('183', 'Medio año'), ('365', 'Un año'), ('730', 'Dos años'), ('1825', 'Cinco años')], default='365', max_length=200)),
                ('meta', models.CharField(max_length=200)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema', to='ahorro.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to='ahorro.sistema')),
            ],
        ),
    ]
