# Generated by Django 3.1.5 on 2021-02-05 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0005_auto_20210205_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='meta',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Usa únicamente números', regex='\\D')]),
        ),
    ]
