# Generated by Django 3.1.5 on 2021-02-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0016_remove_ahorro_sistemaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='sistemaF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ahorrosF', to='ahorro.cantidadfija'),
            preserve_default=False,
        ),
    ]
