# Generated by Django 3.1.5 on 2021-02-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0018_remove_ahorro_sistemaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='sistemaF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahorrosF', to='ahorro.cantidadfija'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to='ahorro.sistema'),
        ),
    ]
