# Generated by Django 3.1.5 on 2021-02-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahorro', '0020_auto_20210218_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhorrarEsLaMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('not_archived', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(choices=[('0', 'Ahorraré cuando pueda/quiera'), ('1', 'Todos los días'), ('15', 'Cada quince días'), ('30', 'Al mes')], default='0', max_length=200)),
                ('cantidad', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemAM_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ahorro',
            name='sistemaAM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahorrosAM', to='ahorro.ahorrareslameta'),
        ),
    ]
