# Generated by Django 3.1.5 on 2021-08-02 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0023_auto_20210222_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Vamos, a que puedes ahorrar más de 10 pesos')]),
        ),
    ]
