# Generated by Django 3.1.5 on 2021-08-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0025_auto_20210823_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorrareslameta',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahorrareslameta',
            name='push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cantidadfija',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cantidadfija',
            name='push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='push',
            field=models.BooleanField(default=False),
        ),
    ]
