# Generated by Django 3.1.5 on 2021-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0026_auto_20210824_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
