# Generated by Django 3.1.5 on 2021-08-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0028_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
