# Generated by Django 3.1.5 on 2021-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0029_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_acuerdo_aviso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_terminos',
            field=models.BooleanField(default=False),
        ),
    ]
